In [1]:
# Cell 1: Import PyTorch and verify setup

import torch
import numpy as np

# Check versions
print(f"PyTorch version: {torch.__version__}")
print(f"NumPy version:   {np.__version__}")
print(f"CUDA available:  {torch.cuda.is_available()}")
print(f"MPS available:   {torch.backends.mps.is_available()}")  # For Apple Silicon
print(f"Device to use:   {'cuda' if torch.cuda.is_available() else 'cpu'}")


PyTorch version: 2.2.2
NumPy version:   1.26.4
CUDA available:  False
MPS available:   True
Device to use:   cpu


In [2]:
# Cell 1.5: Smart device detection (CPU / CUDA / MPS)

def get_device():
    """Returns the best available device: CUDA > MPS > CPU"""
    if torch.cuda.is_available():
        return torch.device("cuda")
    elif torch.backends.mps.is_available():
        return torch.device("mps")
    else:
        return torch.device("cpu")

device = get_device()
print(f"🎯 Using device: {device}")

# Quick speed comparison
import time

# Create a large tensor on CPU
x_cpu = torch.randn(1000, 1000)

# Time CPU multiplication
start = time.time()
for _ in range(10):
    y = x_cpu @ x_cpu  # Matrix multiplication
cpu_time = time.time() - start
print(f"⏱️  CPU time (10 matrix mults): {cpu_time:.3f} seconds")

# Time MPS multiplication (if available)
if device.type == "mps":
    x_mps = x_cpu.to(device)  # Move tensor to GPU
    # Warm up (first run is slow due to compilation)
    _ = x_mps @ x_mps
    torch.mps.synchronize()  # Wait for GPU to finish
    
    start = time.time()
    for _ in range(10):
        y = x_mps @ x_mps
    torch.mps.synchronize()
    mps_time = time.time() - start
    print(f"⚡ MPS time (10 matrix mults): {mps_time:.3f} seconds")
    print(f"🚀 Speedup: {cpu_time/mps_time:.2f}x faster on MPS!")

🎯 Using device: mps
⏱️  CPU time (10 matrix mults): 0.057 seconds
⚡ MPS time (10 matrix mults): 0.017 seconds
🚀 Speedup: 3.34x faster on MPS!


In [3]:
# Cell 2: Creating tensors - the basics

# Method 1: From a Python list
tensor_1d = torch.tensor([1, 2, 3, 4, 5])
print("1D Tensor (vector):")
print(tensor_1d)
print(f"Shape: {tensor_1d.shape}")
print(f"Dtype: {tensor_1d.dtype}\n")

# Method 2: 2D tensor (matrix)
tensor_2d = torch.tensor([[1, 2, 3], 
                          [4, 5, 6], 
                          [7, 8, 9]])
print("2D Tensor (matrix):")
print(tensor_2d)
print(f"Shape: {tensor_2d.shape}\n")

# Method 3: 3D tensor (like a color image!)
tensor_3d = torch.tensor([[[1, 2], [3, 4]], 
                          [[5, 6], [7, 8]]])
print("3D Tensor (like a mini image):")
print(tensor_3d)
print(f"Shape: {tensor_3d.shape}")

1D Tensor (vector):
tensor([1, 2, 3, 4, 5])
Shape: torch.Size([5])
Dtype: torch.int64

2D Tensor (matrix):
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Shape: torch.Size([3, 3])

3D Tensor (like a mini image):
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])


In [4]:
# Cell 3: Special tensors (zeros, ones, random)

# Tensor of all zeros - useful for initialization
zeros = torch.zeros(3, 4)  # 3 rows, 4 columns
print("Zeros tensor:")
print(zeros)
print(f"Shape: {zeros.shape}\n")

# Tensor of all ones
ones = torch.ones(2, 3)
print("Ones tensor:")
print(ones)
print(f"Shape: {ones.shape}\n")

# Random tensor (values between 0 and 1)
random = torch.rand(2, 3)
print("Random tensor (uniform):")
print(random)
print(f"Shape: {random.shape}\n")

# Random tensor (normal distribution — mean=0, std=1)
random_normal = torch.randn(2, 3)
print("Random tensor (normal distribution):")
print(random_normal)

# Range tensor (like Python's range)
range_tensor = torch.arange(0, 10, 2)  # start, stop, step
print(f"\nRange tensor: {range_tensor}")

Zeros tensor:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Shape: torch.Size([3, 4])

Ones tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Shape: torch.Size([2, 3])

Random tensor (uniform):
tensor([[0.9530, 0.1799, 0.3368],
        [0.5019, 0.6606, 0.5137]])
Shape: torch.Size([2, 3])

Random tensor (normal distribution):
tensor([[ 1.4083,  1.2565, -0.4188],
        [ 0.7788,  1.3806,  0.9032]])

Range tensor: tensor([0, 2, 4, 6, 8])


In [5]:
# Cell 4: Tensor operations - the math

# Create two tensors
a = torch.tensor([[1., 2.], [3., 4.]])
b = torch.tensor([[5., 6.], [7., 8.]])

print("Tensor a:")
print(a)
print("\nTensor b:")
print(b)

# 1. Element-wise addition
print("\n➕ a + b (element-wise):")
print(a + b)

# 2. Element-wise multiplication (NOT matrix multiplication!)
print("\n✖️  a * b (element-wise):")
print(a * b)

# 3. Matrix multiplication (the @ symbol)
print("\n🔢 a @ b (matrix multiplication):")
print(a @ b)

# 4. Scalar operations
print("\n📊 a * 10 (scalar):")
print(a * 10)

# 5. Aggregations
print(f"\n📈 Sum of a: {a.sum().item()}")
print(f"📈 Mean of a: {a.mean().item()}")
print(f"📈 Max of a: {a.max().item()}")
print(f"📈 Min of a: {a.min().item()}")

Tensor a:
tensor([[1., 2.],
        [3., 4.]])

Tensor b:
tensor([[5., 6.],
        [7., 8.]])

➕ a + b (element-wise):
tensor([[ 6.,  8.],
        [10., 12.]])

✖️  a * b (element-wise):
tensor([[ 5., 12.],
        [21., 32.]])

🔢 a @ b (matrix multiplication):
tensor([[19., 22.],
        [43., 50.]])

📊 a * 10 (scalar):
tensor([[10., 20.],
        [30., 40.]])

📈 Sum of a: 10.0
📈 Mean of a: 2.5
📈 Max of a: 4.0
📈 Min of a: 1.0


In [6]:
# Cell 5: Reshaping tensors - critical for neural networks!

# Create a tensor with 12 elements
x = torch.arange(12)
print("Original tensor (12 elements):")
print(x)
print(f"Shape: {x.shape}\n")

# Reshape to 3x4 matrix
x_3x4 = x.reshape(3, 4)
print("Reshaped to 3x4:")
print(x_3x4)
print(f"Shape: {x_3x4.shape}\n")

# Reshape to 2x6 matrix
x_2x6 = x.reshape(2, 6)
print("Reshaped to 2x6:")
print(x_2x6)
print(f"Shape: {x_2x6.shape}\n")

# Reshape to 3D (2x2x3)
x_3d = x.reshape(2, 2, 3)
print("Reshaped to 3D (2x2x3):")
print(x_3d)
print(f"Shape: {x_3d.shape}\n")

# The magic -1: "figure out this dimension automatically"
x_auto = x.reshape(4, -1)  # 4 rows, PyTorch calculates columns
print("Auto-reshape (4, -1):")
print(x_auto)
print(f"Shape: {x_auto.shape}\n")

# Flatten a tensor
x_flat = x_3x4.flatten()
print("Flattened back to 1D:")
print(x_flat)
print(f"Shape: {x_flat.shape}")

Original tensor (12 elements):
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Shape: torch.Size([12])

Reshaped to 3x4:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Shape: torch.Size([3, 4])

Reshaped to 2x6:
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
Shape: torch.Size([2, 6])

Reshaped to 3D (2x2x3):
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
Shape: torch.Size([2, 2, 3])

Auto-reshape (4, -1):
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
Shape: torch.Size([4, 3])

Flattened back to 1D:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Shape: torch.Size([12])


In [7]:
# Cell 6: NumPy <-> PyTorch conversion (crucial for OpenCV integration!)

# Create a NumPy array (like what you get from cv2.imread)
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Original NumPy array:")
print(numpy_array)
print(f"Type: {type(numpy_array)}")
print(f"Shape: {numpy_array.shape}\n")

# Convert NumPy → PyTorch tensor
tensor_from_numpy = torch.from_numpy(numpy_array)
print("Converted to PyTorch tensor:")
print(tensor_from_numpy)
print(f"Type: {type(tensor_from_numpy)}")
print(f"Shape: {tensor_from_numpy.shape}\n")

# Convert PyTorch tensor → NumPy array
back_to_numpy = tensor_from_numpy.numpy()
print("Converted back to NumPy:")
print(back_to_numpy)
print(f"Type: {type(back_to_numpy)}\n")

# 🎯 REAL EXAMPLE: Load an image with OpenCV and convert to tensor
import cv2
import os

# Load one of your existing images
image_path = os.path.expanduser("/Users/mac/data/raw/samples/flower.jpg")
image_bgr = cv2.imread(image_path)
image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)  # OpenCV loads BGR, we want RGB

print(f"📷 Loaded image shape (NumPy): {image_rgb.shape}")
print(f"📷 Dtype: {image_rgb.dtype}")

# Convert image to PyTorch tensor
image_tensor = torch.from_numpy(image_rgb)
print(f"\n🔥 Image as PyTorch tensor:")
print(f"Shape: {image_tensor.shape}")
print(f"Dtype: {image_tensor.dtype}")
print(f"Min value: {image_tensor.min().item()}, Max value: {image_tensor.max().item()}")

Original NumPy array:
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Shape: (2, 3)

Converted to PyTorch tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])

Converted back to NumPy:
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>

📷 Loaded image shape (NumPy): (534, 800, 3)
📷 Dtype: uint8

🔥 Image as PyTorch tensor:
Shape: torch.Size([534, 800, 3])
Dtype: torch.uint8
Min value: 0, Max value: 255


In [8]:
# Verify folder structure
import os

paths_to_confirm = [
    "~/data/raw/samples/",
    "~/ai_id_detection/data/raw/samples/",
    "~/ai_id_detection/notebooks/",
]

for p in paths_to_confirm:
    full = os.path.expanduser(p)
    exists = os.path.exists(full)
    print(f"{'✅' if exists else '❌'} {p} → {full}")
    if exists and os.path.isdir(full):
        try:
            contents = os.listdir(full)[:5]  # First 5 items
            print(f"   Contents: {contents}")
        except:
            pass
    print()
    

✅ ~/data/raw/samples/ → /Users/mac/data/raw/samples/
   Contents: ['document.jpg', '.DS_Store', 'portrait.jpg', 'building.jpg', 'flower.jpg']

❌ ~/ai_id_detection/data/raw/samples/ → /Users/mac/ai_id_detection/data/raw/samples/

✅ ~/ai_id_detection/notebooks/ → /Users/mac/ai_id_detection/notebooks/
   Contents: ['anaconda_projects', '04_pytorch_tensors.ipynb', '.ipynb_checkpoints']



In [9]:
# Cell 7: Tensor attributes and moving to GPU/MPS

# Create a sample tensor
x = torch.randn(3, 4)
print("Sample tensor x:")
print(x)

# All important attributes
print(f"\n📏 Shape:    {x.shape}")
print(f"🔢 Dtype:    {x.dtype}")
print(f"📍 Device:   {x.device}")
print(f"🎯 Requires gradient: {x.requires_grad}")
print(f"📊 Number of elements: {x.numel()}")
print(f"📐 Dimensions: {x.dim()}")

# Move tensor to MPS (your Mac's GPU!)
if torch.backends.mps.is_available():
    x_mps = x.to("mps")
    print(f"\n🚀 Moved to MPS:")
    print(f"Device: {x_mps.device}")
    
    # Do math on MPS
    y_mps = x_mps * 2
    print(f"Math on MPS works! Shape: {y_mps.shape}")
    
    # Move back to CPU (needed to convert to NumPy)
    x_back = x_mps.to("cpu")
    print(f"\n⬅️  Moved back to CPU:")
    print(f"Device: {x_back.device}")

# Change dtype (float32 → float64, etc.)
x_int = x.to(torch.int32)
print(f"\n🔄 Converted to int32:")
print(f"Dtype: {x_int.dtype}")
print(x_int)

Sample tensor x:
tensor([[ 0.0673, -0.1565,  1.3023, -2.1966],
        [ 0.1898,  1.4708,  1.6332,  2.2786],
        [ 0.8846,  1.5694, -1.4481, -0.2393]])

📏 Shape:    torch.Size([3, 4])
🔢 Dtype:    torch.float32
📍 Device:   cpu
🎯 Requires gradient: False
📊 Number of elements: 12
📐 Dimensions: 2

🚀 Moved to MPS:
Device: mps:0
Math on MPS works! Shape: torch.Size([3, 4])

⬅️  Moved back to CPU:
Device: cpu

🔄 Converted to int32:
Dtype: torch.int32
tensor([[ 0,  0,  1, -2],
        [ 0,  1,  1,  2],
        [ 0,  1, -1,  0]], dtype=torch.int32)


In [ ]:
Create a handoff prompt for a new chat that contains everything i 
need to continue this project without losing context
and it should flow the same format that we are flowing now